name: urdig
adopt-info: urdig
summary: Tool to grab information about devices via udev, written in Rust
description: |
  urdig is a tool, which can be used to display
  informations about several (udev)-devices.
base: core20
confinement: strict
parts:
  urdig:
    build-packages: [ libudev-dev, pkg-config ]
    plugin: rust
    source: https://github.com/ph0llux/urdig.git
    override-pull: |
      snapcraftctl pull
      version="$(git describe --tags --abbrev=0)"
      [ -n "$(echo $version)" ] && grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
apps:
  urdig:
    command: bin/urdig
architectures:
  - build-on: [amd64,arm64]